apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    federation.alpha.kubernetes.io/federation-name: federation
  labels:
    app: federated-cluster
  name: fellowship-federation-apiserver-volume
  namespace: federation-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
